[package]
name = "unifed-fedscale"
version = "0.0.0"
keywords = ["federated learning", "machine learning"]
description = "FedScale"
language = "python"
install_script = """


if { conda env list | grep 'colink-protocol-unifed-fedscale'; } >/dev/null 2>&1; then
    conda env remove -n colink-protocol-unifed-fedscale
fi

git clone https://github.com/xmhuangzhen/FedScale.git

source install_colink_version.sh

conda init bash
conda env create -f environment.yml
conda activate colink-protocol-unifed-fedscale

cd FedScale
git checkout 0328update
pip install -e .
cd ..

touch record_exp.txt

pip install --upgrade pip
pip install flbenchmark
pip install nest_asyncio
pip install pyyaml
pip install colink
pip install wandb
pip install pytest
pip install -e .
 
"""
entrypoint = """
conda activate colink-protocol-unifed-fedscale
source install_colink_version.sh
unifed-fedscale > debug.txt 2>&1
"""
