[package]
name = "unifed-fedscale"
version = "0.0.0"
keywords = ["federated learning", "machine learning"]
description = "FedScale"
language = "python"
install_script = """

if { conda env list | grep 'colink-protocol-unifed-fedscale'; } >/dev/null 2>&1; then
    conda env remove -n colink-protocol-unifed-fedscale
fi

git clone https://github.com/xmhuangzhen/FedScale.git
cd FedScale
git checkout 0328update
conda env create -f environment.yml -y
conda activate colink-protocol-unifed-fedscale
pip install -e .
cd ..



pip install --upgrade pip
pip install flbenchmark
pip install nest_asyncio
pip install pyyaml
pip install colink
pip install wandb
pip install pytest
pip install -e .
 
"""
entrypoint = """
conda activate colink-protocol-unifed-fedscale
unifed-fedscale > debug.txt 2>&1
"""
